### ISSUE TITLE
Top down / bottom up shades

### ISSUE THREAD

**Issue by charleypick** [GvnCampbell/homebridge-powerview#3]
Thanks for writing this awesome plugin, it works very well! I have top down / bottom up shades. A challenge I have is if I use the Hunter Douglas app to lower the top some and then use this plug-in to raise the bottom of the shades, the bottom will rise to where the shade is open at the top and stop. It would be amazing if we could set a flag to True for top-down/bottom-up to raise the top when a command is set to raise the bottom. If you can find the API command to do that, I would be happy to test.

**Comment by GvnCampbell** [comment]
Thanks for the input.  Its very hard trying to find the api calls and test them when I don't have the blinds.  Unfortunately I only have the roller shades to play with.

**Comment by GvnCampbell** [comment]
Closing this issue for now.  If anything changes I will update the readme with the supported devices.
