### ISSUE TITLE
Set up plugin in npm

### ISSUE THREAD

**Issue by mteper** [GvnCampbell/homebridge-powerview#4]
Please add to npm for ease of installation and updates. Thank you!!

**Comment by mteper** [comment]
https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by chris-erickson** [comment]
Alternatively, `npm install -g GvnCampbell/homebridge-powerview`

**Comment by GvnCampbell** [comment]
I have included that line in the installation instructions.  So much easier.  Thanks for the info.
