### ISSUE TITLE
Shades Populate in Home App but do not Respond

### ISSUE THREAD

**Issue by trobinson65** [GvnCampbell/homebridge-powerview#6]
I have configured this plugin within home bridge and each power view shade populates with the proper names in the home app but shows incorrect current state and trying to open or close the shades does not activate the unit.

Hub Gen 2 Firmware Ver. 2.0.589
Shade Type Powerview Duette & Applause Honeycomb Bottom Up

**Comment by GvnCampbell** [comment]
Unfortunately I only have the Gen1 hub and roller shades to do any sort of debugging/testing/api discovery on.  Its pretty difficult to do any of this remotely as everything is undocumented.

If there is somebody that understands the code and have these devices and wants to contribute I would be more than happy to let them.

**Comment by trobinson65** [comment]
That could very well explain the difference. I appreciate the reply.

**Comment by GvnCampbell** [comment]
I will close this issue. If anything changes in the future I will update the readme.
